version: "3.8"
services:
# database
  postgres-rinha:
    image: postgres:16-alpine
    env_file:
      - .env
    container_name: postgres-rinha
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5431:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
