version: "3.8"
services:

## limites
## cpus 1.5
## memory 550MB

  api-01: &api
    # image: api
    build:
      context: .
    container_name: api-01
    hostname: api-01
    environment:
      DB_CONNECTION_STRING: postgres://user:password@postgres:5432/rinha_db?sslmode=disable
      MAX_CONN: 20
      MIN_CONN: 5
    ports:
      - "8080:3001"
      # - "3333:3333" # profiler port
    depends_on:
      - postgres
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "90MB"

  api-02:
    <<: *api
    container_name: api-02
    hostname: api-02
    ports:
      - "8081:3001"
      # - "3334:3333" # profiler port


  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.25.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api-01:
        condition: service_started
      api-02:
        condition: service_started
    restart: on-failure
    ports:
      - "9999:9999"
      # - "9998:9998" # profiler port
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"


# database
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: rinha_db
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "320MB"
          

# UI pgadmin4
  # pgadmin:
  #   image: dpage/pgadmin4:8.2
  #   container_name: pgadmin
  #   depends_on:
  #     - postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: jp@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - 8082:80
  #   volumes:
  #     - ./.data/pgadmin:/var/lib/pgadmin
      
networks:
  default:
    driver: bridge
    name: network-rinha