### Create transaction
POST http://localhost:9999/clientes/1/transacoes HTTP/1.1
content-type: application/json

{
    "valor": 30000,
    "tipo" : "d",
    "descricao" : "teste"
}

### Create extrato
GET http://localhost:9999/clientes/1/extrato HTTP/1.1
content-type: application/json